require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.0

#################### Bundler ###########################

Bundler/OrderedGems:
  Enabled: false
  ConsiderPunctuation: true

#################### Layout ###########################
Layout/EmptyLinesAroundAttributeAccessor:
  StyleGuide: '#empty-lines-around-attribute-accessor'
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

#################### Lint ##################################

Lint/AmbiguousBlockAssociation:
  StyleGuide: '#syntax'
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - 'app/components/**/*'

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/FloatComparison:
  StyleGuide: '#float-comparison'
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

#################### Metrics ###############################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'db/seeds.rb'
    - 'Guardfile'
    - 'spec/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  StyleGuide: '#short-methods'
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  StyleGuide: '#too-many-params'
  Enabled: false

#################### Naming ##############################
Naming/PredicateName:
  StyleGuide: '#bool-methods-qmark'
  Enabled: true
  ForbiddenPrefixes:
    - is_
  Exclude:
    - 'spec/**/*'

#################### Style ###############################
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashAsLastArrayItem:
  StyleGuide: '#hash-literal-as-last-array-item'
  Enabled: true
  EnforcedStyle: no_braces

Style/HashSyntax:
  StyleGuide: '#hash-literals'
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Style/RedundantFetchBlock:
  Reference: 'https://github.com/JuanitoFatas/fast-ruby#hashfetch-with-argument-vs-hashfetch--block-code'
  Enabled: true

Style/RedundantFileExtensionInRequire:
  StyleGuide: '#no-explicit-rb-to-require'
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  StyleGuide: '#consistent-string-literals'
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/TrailingCommaInArguments:
  StyleGuide: '#no-trailing-params-comma'
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  StyleGuide: '#no-trailing-array-commas'
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInBlockArgs:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

# Rails cops from rubocop-rails
# https://github.com/rubocop-hq/rubocop-rails/blob/master/config/default.yml
Rails/ActiveRecordCallbacksOrder:
  StyleGuide: 'https://rails.rubystyle.guide/#callbacks-order'
  Enabled: true

Rails/DefaultScope:
  StyleGuide: 'https://rails.rubystyle.guide#avoid-default-scope'
  Enabled: true

Rails/FilePath:
  EnforcedStyle: slashes

Rails/FindById:
  StyleGuide: 'https://rails.rubystyle.guide/#find'
  Enabled: true

Rails/Inquiry:
  StyleGuide: 'https://rails.rubystyle.guide/#inquiry'
  Enabled: true

Rails/MailerName:
  StyleGuide: 'https://rails.rubystyle.guide/#mailer-name'
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckId:
  StyleGuide: 'https://rails.rubystyle.guide/#ids'
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  StyleGuide: 'https://rails.rubystyle.guide/#inline-rendering'
  Enabled: true

Rails/RenderPlainText:
  StyleGuide: 'https://rails.rubystyle.guide/#plain-text-rendering'
  Enabled: true

Rails/ShortI18n:
  StyleGuide: 'https://rails.rubystyle.guide/#short-i18n'
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/WhereExists:
  Enabled: true

Rails/ContentTag:
  Enabled: false

# RSpec cops from rubocop-rspec
# https://github.com/rubocop-hq/rubocop-rspec/blob/master/config/default.yml
RSpec/DescribeClass:
  Enabled: true
  StyleGuide: 'https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/DescribeClass'
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/system/**/*'
    - 'spec/tasks/**/*'

RSpec/DescribedClassModuleWrapping:
  Enabled: true
  StyleGuide: 'https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/DescribedClassModuleWrapping'

RSpec/ExampleLength:
  Enabled: true
  Max: 15
  StyleGuide: 'https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ExampleLength'

RSpec/MessageExpectation:
  Enabled: true
  EnforcedStyle: allow

RSpec/MultipleMemoizedHelpers:
  Enabled: false
  StyleGuide: 'https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/MultipleMemoizedHelpers'

RSpec/MultipleExpectations:
  Enabled: true
  Max: 8
  StyleGuide: 'https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/MultipleExpectations'
