source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"

gem "active_model_serializers", "~> 0.8.1"
gem "bcrypt", "~> 3.1", ">= 3.1.16"
gem "bootsnap", ">= 1.4.4", require: false
gem "jwt", "~> 2.2", ">= 2.2.2"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "rails", "~> 6.1.3", ">= 6.1.3.1"

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails", "~> 6.1"
  gem "pundit", "~> 2.1"
  gem "pundit-matchers", "~> 1.6"
  gem "rspec-rails", "~> 5.0", ">= 5.0.1"
  gem "shoulda-matchers", "~> 4.5", ">= 4.5.1"
  gem "timecop", "~> 0.9.4"
  gem "vcr", "~> 6.0"
  gem "webmock", "~> 3.12", ">= 3.12.2"
end

group :development do
  gem "listen", "~> 3.3"
  gem "rubocop", "~> 1.12", ">= 1.12.1"
  gem "rubocop-rails", "~> 2.9", ">= 2.9.1"
  gem "rubocop-rspec", "~> 2.2"
  gem "spring"
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
